# Generated by Django 3.2.5 on 2022-11-21 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190904_0957'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='detected',
            old_name='emp_id',
            new_name='user_id',
        ),
    ]
