# Generated by Django 3.2.5 on 2022-11-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20221121_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('website_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=500)),
            ],
        ),
    ]
