# Generated by Django 3.2.5 on 2022-12-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='website',
            name='website_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
